--PROJECT_TABLE ����
CREATE TABLE PROJECT_TABLE(
PROJECT_ID NUMBER,
PROJECT_NAME VARCHAR2(1000)
);

--PK ���� PROJECT_TABLE(PROJECT_ID)
ALTER TABLE PROJECT_TABLE
ADD CONSTRAINT PK_PROJECT_ID PRIMARY KEY(PROJECT_ID);

drop table project_table;

--PROJECT_NO ������
CREATE SEQUENCE PROJECT_SEQ -- ������ �̸�
START WITH 1000  --1000���� ����
INCREMENT BY 1 --1�� ����
NOMAXVALUE  --�Ѱ谡 ����
NOMINVALUE; --�ּҰ� X

ALTER TABLE PROJECT_TABLE 
ADD UNIQUE(PROJECT_NAME);

ALTER TABLE PROJECT_TABLE 
ADD PROJECT_CHOICE number;

alter table project_table
drop column project_choice;

commit;

INSERT INTO PROJECT_TABLE(PROJECT_ID, PROJECT_NAME)
VALUES(PROJECT_SEQ.nextval, 'SSANGYONG');

select *
from project_table;


