--PROJECT_TABLE 생성
CREATE TABLE PROJECT_TABLE(
PROJECT_ID NUMBER,
PROJECT_NAME VARCHAR2(1000)
);

--PK 설정 PROJECT_TABLE(PROJECT_ID)
ALTER TABLE PROJECT_TABLE
ADD CONSTRAINT PK_PROJECT_ID PRIMARY KEY(PROJECT_ID);

drop table project_table;

--PROJECT_NO 시퀀스
CREATE SEQUENCE PROJECT_SEQ -- 시퀀스 이름
START WITH 1000  --1000부터 시작
INCREMENT BY 1 --1씩 증가
NOMAXVALUE  --한계가 없이
NOMINVALUE; --최소값 X

ALTER TABLE PROJECT_TABLE 
ADD UNIQUE(PROJECT_NAME);

commit;

INSERT INTO PROJECT_TABLE(PROJECT_ID, PROJECT_NAME)
VALUES(PROJECT_SEQ.nextval, 'SSANGYONG');

select * from project_Table;