CREATE TABLE COMMENT_TABLE(
USER_ID VARCHAR2(50) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
BOARD_NO NUMBER,
COMMENT_NO NUMBER,
COMMENT_WRITE_DATE DATE not null,
COMMENT_CONTENTS VARCHAR2(4000) NOT NULL
);  

commit;

commit;

drop table comment_table;

select * from comment_table;

--FK ���� USER_TABLE(USER_ID)
ALTER TABLE COMMENT_TABLE 
ADD CONSTRAINT FK_COMMENT_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(USER_ID);

select * from user_table;


--FK ���� BOARD_TABLE(BOARD_NO)
ALTER TABLE COMMENT_TABLE
ADD CONSTRAINT FK_COMMENT_BOARD_NO FOREIGN KEY(BOARD_NO) REFERENCES BOARD_TABLE ON DELETE CASCADE;



--COMMENT_NO ������
CREATE SEQUENCE COMMENT_SEQ -- ������ �̸�
START WITH 1  --1���� ����
INCREMENT BY 1 --1�� ����
NOMAXVALUE  --�Ѱ谡 ����
NOMINVALUE; --�ּҰ� X

--댓글 삽입
insert into comment_table(BOARD_NO, comment_no, comment_contents, user_id, user_name, comment_write_date)
values('135', comment_seq.nextval, '테스트1', '1', '1', sysdate)
;

COMMIT;
DELETE FROM COMMENT_TABLE;

--댓글 목록
SELECT BOARD_NO, COMMENT_NO, COMMENT_CONTENTS, C.USER_ID, C.USER_NAME, COMMENT_WRITE_DATE
FROM COMMENT_TABLE C, USER_TABLE U
WHERE C.USER_ID = U.USER_ID
AND BOARD_NO = 130
ORDER BY COMMENT_NO
;


SELECT C.BOARD_NO, COMMENT_NO, COMMENT_CONTENTS, C.USER_ID, C.USER_NAME, COMMENT_WRITE_DATE
FROM BOARD_TABLE B, COMMENT_TABLE C, USER_TABLE U
WHERE C.USER_ID = U.USER_ID
;

SELECT B.BOARD_NO, COMMENT_NO, COMMENT_CONTENTS, C.USER_ID, C.USER_NAME, COMMENT_WRITE_DATE
FROM BOARD_TABLE B, COMMENT_TABLE C, USER_TABLE U
WHERE B.BOARD_NO = C.BOARD_NO
;

select* from comment_table
;

commit;

select* from board_table;