CREATE TABLE TODO_LIST_TABLE(
TODO_NO NUMBER,
CATEGORY_ID NUMBER,
TODO_LIST VARCHAR2(1000),
TODO_START_DATE DATE,
TODO_END_DATE DATE,
TODO_PRIORITY VARCHAR2(15),
TODO_NOTE VARCHAR2(500),
TODO_COMPLETE VARCHAR2(15) DEFAULT 'N'
);

ALTER TABLE TODO_LIST_TABLE 
ADD PROJECT_ID NUMBER;

ALTER TABLE TODO_LIST_TABLE
ADD CONSTRAINT PK_TODO_NO PRIMARY KEY(TODO_NO);

ALTER TABLE TODO_LIST_TABLE
ADD CONSTRAINT FK_TODO_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_TABLE;

CREATE SEQUENCE TODO_SEQ -- 시퀀스 이름
START WITH 1000  --1부터 시작
INCREMENT BY 1 --1씩 증가
NOMAXVALUE  --한계가 없이
NOMINVALUE; --최소값 X

--TODO 추가 쿼리
INSERT INTO TODO_LIST_TABLE
VALUES (TODO_SEQ.NEXTVAL ,2023, 'LIST 04', SYSDATE, SYSDATE, 'M', 'TEST NOTE 4', '0', 1040);
 


DELETE TODO_LIST_TABLE WHERE TODO_NO=1024;
commit;

--TODO_NO SELECT
SELECT MAX(TODO_NO) FROM TODO_LIST_TABLE;

--TODO VIEW
SELECT M.TODO_NO, L.CATEGORY_ID, L.TODO_LIST, L.TODO_START_DATE, 
  				L.TODO_END_DATE, L.TODO_PRIORITY, L.TODO_NOTE, L.TODO_COMPLETE, M.MEMBER_NICKNAME 
			FROM TODO_LIST_TABLE L, TODO_MEMBER_TABLE M 
			WHERE L.TODO_NO = M.TODO_NO AND 
			M.TODO_NO = #{todo_no};
            
SELECT TODO_LIST, TODO_START_DATE, TODO_END_DATE, TODO_PRIORITY, TODO_NOTE 
FROM TODO_LIST_TABLE 
WHERE TODO_NO=1026;

--TODO VIEWLIST
SELECT TODO_NO, TODO_LIST, TODO_PRIORITY, TODO_COMPLETE 
FROM TODO_LIST_TABLE 
WHERE CATEGORY_ID = 2001
ORDER BY TODO_NO DESC;

--TODO COMPLETE 
SELECT TODO_COMPLETE 
FROM TODO_LIST_TABLE 
WHERE TODO_NO = 1010;

UPDATE TODO_LIST_TABLE SET TODO_COMPLETE='1' WHERE TODO_NO=1009;
UPDATE TODO_LIST_TABLE SET TODO_COMPLETE='0' WHERE TODO_NO=1009;

--TODO MODIFY
UPDATE TODO_LIST_TABLE SET TODO_LIST='KIM', TODO_START_DATE='17-07-12', TODO_END_DATE='17-07-14', TODO_PRIORITY='중', TODO_NOTE='AAAALLLLL123' WHERE TODO_NO=1027;

SELECT TODO_COMPLETE FROM TODO_LIST_TABLE WHERE TODO_NO = 1027;

SELECT to_char(todo_start_date, 'mm/dd/yyyy') FROM TODO_LIST_TABLE;
COMMIT; 
ROLLBACK;
DELETE FROM PROJECT_TABLE;

SELECT * FROM CATEGORY_TABLE C, TODO_LIST_TABLE T WHERE C.CATEGORY_ID=T.CATEGORY_ID;
SELECT C.CATEGORY_NAME, COUNT(T.TODO_COMPLETE), SUM(T.TODO_COMPLETE) FROM CATEGORY_TABLE C, TODO_LIST_TABLE T WHERE C.CATEGORY_ID=T.CATEGORY_ID GROUP BY C.CATEGORY_NAME;
--CHART
SELECT C.CATEGORY_NAME, COUNT(T.TODO_COMPLETE) todo_cnt, SUM(T.TODO_COMPLETE) todo_complete_cnt
FROM CATEGORY_TABLE C, TODO_LIST_TABLE T 
WHERE C.CATEGORY_ID=T.CATEGORY_ID AND 
C.PROJECT_ID = 1062
GROUP BY C.CATEGORY_NAME;

SELECT * FROM TODO_LIST_TABLE;

-------------------------------------------------------

CREATE TABLE TODO_MEMBER_TABLE(
TODO_NO NUMBER,
MEMBER_NICKNAME VARCHAR2(50)
);


ALTER TABLE TODO_MEMBER_TABLE
ADD CONSTRAINT FK_TODO_MEMBER_NO FOREIGN KEY(TODO_NO) REFERENCES TODO_LIST_TABLE ON DELETE CASCADE;
ALTER TABLE TODO_MEMBER_TABLE DROP CONSTRAINT FK_TODO_MEMBER_NO;

SELECT * FROM TODO_MEMBER_TABLE;
DELETE FROM TODO_MEMBER_TABLE;

COMMIT;

INSERT INTO TODO_MEMBER_TABLE 
VALUES (1080, '쨩쨩이');

SELECT MEMBER_NICKNAME FROM TODO_MEMBER_TABLE WHERE TODO_NO=1080;
