--BOARD_TABLE ����
CREATE TABLE BOARD_TABLE(
CATEGORY_ID NUMBER,
BOARD_TITLE VARCHAR2(100) NOT NULL,
BOARD_NO NUMBER,
BOARD_CONTENTS varchar2(4000),
USER_ID varchar2(50) NOT NULL,
BOARD_WRITE_DATE date NOT NULL,
BOARD_MODIFY_DATE date NOT NULL,
BOARD_HITCOUNT number DEFAULT 0 NOT NULL,
BOARD_COMMENT_COUNT number default 0,
USER_NAME VARCHAR2(20) NOT NULL
);

select* from board_table;

--FK ���� BOARD_TABLE(USER_ID)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT FK_BOARD_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_TABLE;


--FK ���� CATEGORY_TABLE(CATEGORY_ID)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT FK_BOARD_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_TABLE;

--���̺� �÷��� ����
ALTER TABLE BOARD_TABLE
RENAME COLUMN BOARD_CATEGORY_ID TO CATEGORY_ID;

ALTER TABLE BOARD_TABLE
RENAME COLUMN BOARD_COUNT TO BOARD_HITCOUNT;


ALTER TABLE BOARD_TABLE 
ADD BOARD_NOTICE VARCHAR2(20);

ALTER TABLE BOARD_TABLE 
ADD USER_NAME VARCHAR2(20) not null;

ALTER TABLE BOARD_TABLE 
ADD BOARD_COMMENT_COUNT number default 0;


commit;

--PK ���� BOARD_TABLE(BOARD_NO)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO);


--BOARD_NO ������
CREATE SEQUENCE BOARD_SEQ -- ������ �̸�
START WITH 1  --1���� ����
INCREMENT BY 1 --1�� ����
NOMAXVALUE  --�Ѱ谡 ����
NOMINVALUE; --�ּҰ� X

drop sequence board_seq;

commit;


--CATEGORY_ID ã��
--SELECT *
--FROM BOARD_TABLE B, CATEGORY_TABLE C
--WHERE B.CATEGORY_ID = C.CATEGORY_ID AND
--C.CATEGORY_NAME = '����' AND
--C.PROJECT_ID = 1001;


--board �߰� ����
INSERT INTO BOARD_TABLE (CATEGORY_ID, BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_HITCOUNT, BOARD_NOTICE)
VALUES (2001 ,board_seq.nextval, 'TITLE 01', 'CONTENTS 01', '1244234', sysdate, sysdate, 0, 'N');

select * from BOARD_TABLE;
            
--board ����Ʈ ����
SELECT BOARD_TITLE, BOARD_WRITER, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_COUNT
FROM BOARD_TABLE
ORDER BY BOARD_NO DESC;

--board Ȯ�� ����
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, BOARD_WRITER, BOARD_WRITE_DATE, BOARD_COUNT
FROM BOARD_TABLE
WHERE BOARD_NO = 4;

--board ��ȸ�� ����
UPDATE BOARD_TABLE
SET BOARD_COUNT = BOARD_COUNT + 1
WHERE BOARD_NO = 4;

---------------------------
select *
from board_table;

commit;

		INSERT INTO BOARD_TABLE(CATEGORY_ID, BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE)
			VALUES (2023, board_seq.nextval, 'titleTeswefwefwegwergergergdfgergergdfgergergerggdfgergt24', 'contentsTest02', '1', sysdate, sysdate);

SELECT BOARD_NO, BOARD_TITLE, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_HITCOUNT, TO_CHAR(BOARD_WRITE_DATE, 'mon')
			FROM BOARD_TABLE
			ORDER BY BOARD_NO DESC;

select TO_CHAR(SYSDATE, 'MONTH'), TO_CHAR(SYSDATE, 'MON')
from dual;
      

SELECT BOARD_NO, BOARD_TITLE, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_HITCOUNT
FROM BOARD_TABLE B, CATEGORY_TABLE C, PROJECT_TABLE P
WHERE B.CATEGORY_ID = C.CATEGORY_ID
AND C.CATEGORY_NAME = '기타'
AND P.PROJECT_NAME = '프로젝트테스트01'
ORDER BY BOARD_NO 
;


SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_HITCOUNT,
 (SELECT COUNT(*) FROM COMMENT_TABLE WHERE BOARD_NO=B.BOARD_NO) AS recnt
FROM BOARD_TABLE B, CATEGORY_TABLE C, PROJECT_TABLE P
WHERE B.CATEGORY_ID = C.CATEGORY_ID
AND C.CATEGORY_NAME = '아리따움'
AND P.PROJECT_NAME = 'CHAPPIE'
ORDER BY BOARD_NO 
;

select * from board_table;

commit;

UPDATE BOARD_TABLE 
SET 
BOARD_TITLE='KIM', 
BOARD_CONTENTS='board_contents', 
BOARD_MODIFY_DATE=sysdate
WHERE BOARD_NO = 94
and user_id = '1'
;

INSERT INTO BOARD_TABLE(CATEGORY_ID, BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE)
VALUES (2023, board_seq.nextval, 'titleTeswefwefwegwergergergdfgergergdfgergergerggdfgergt24', 'contentsTest02', '1', sysdate, sysdate);



