--BOARD_TABLE 생성
CREATE TABLE BOARD_TABLE(
BOARD_CATEGORY_ID NUMBER,
BOARD_TITLE VARCHAR2(100) NOT NULL,
BOARD_NO NUMBER,
BOARD_CONTENTS varchar2(4000),
USER_ID varchar2(50) NOT NULL,
BOARD_WRITE_DATE date NOT NULL,
BOARD_MODIFY_DATE date NOT NULL,
BOARD_COUNT number DEFAULT 0 NOT NULL
);

--FK 설정 BOARD_TABLE(USER_ID)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT FK_BOARD_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_TABLE;


--FK 설정 CATEGORY_TABLE(CATEGORY_ID)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT FK_BOARD_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_TABLE;

--테이블 컬럼명 변경
ALTER TABLE BOARD_TABLE
RENAME COLUMN BOARD_CATEGORY_ID TO CATEGORY_ID;


drop table board_table;

commit;

--PK 설정 BOARD_TABLE(BOARD_NO)
ALTER TABLE BOARD_TABLE
ADD CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO);


--BOARD_NO 시퀀스
CREATE SEQUENCE BOARD_SEQ -- 시퀀스 이름
START WITH 1  --1부터 시작
INCREMENT BY 1 --1씩 증가
NOMAXVALUE  --한계가 없이
NOMINVALUE; --최소값 X

drop sequence board_seq;

commit;

--board 추가 쿼리
INSERT INTO BOARD_TABLE(CATEGORY_ID,BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, USER_ID, BOARD_WRITE_DATE, BOARD_MODIFY_DATE)
VALUES (2001 ,board_seq.nextval, 'TITLE 01', 'CONTENTS 01', '1', sysdate, sysdate);
            
--board 리스트 쿼리
SELECT BOARD_NO, BOARD_TITLE, BOARD_WRITER, BOARD_WRITE_DATE, BOARD_MODIFY_DATE, BOARD_COUNT
FROM BOARD_TABLE
ORDER BY BOARD_NO DESC;

--board 확인 쿼리
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENTS, BOARD_WRITER, BOARD_WRITE_DATE, BOARD_COUNT
FROM BOARD_TABLE
WHERE BOARD_NO = 4;

--board 조회수 쿼리
UPDATE BOARD_TABLE
SET BOARD_COUNT = BOARD_COUNT + 1
WHERE BOARD_NO = 4;

---------------------------
select *
from board_table;

commit;

