--MEMBER_TABLE 생성
CREATE TABLE MEMBER_TABLE(
PROJECT_ID NUMBER,
MEMBER_NICKNAME VARCHAR2(50),
MEMBER_RANK VARCHAR2(20),
USER_ID VARCHAR2(50)
);

--FK 설정 MEMBER_TABLE(USER_ID)
ALTER TABLE MEMBER_TABLE
ADD CONSTRAINT FK_MEMBER_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER_TABLE;

--FK 설정 MEMBER_TABLE(PROJECT_ID)
ALTER TABLE MEMBER_TABLE
ADD CONSTRAINT FK_MEMBER_PROJECT_ID FOREIGN KEY(PROJECT_ID) REFERENCES PROJECT_TABLE;


commit;

INSERT INTO MEMBER_TABLE(PROJECT_ID, MEMBER_NICKNAME, MEMBER_RANK, USER_ID)
VALUES(1003, 'qqq', 'n', '5');

select * from member_table;

select member_nickname from member_table where project_id = 1003;