CREATE TABLE TODO_LIST_TABLE(
TODO_NO NUMBER,
CATEGORY_ID NUMBER,
TODO_LIST VARCHAR2(1000),
TODO_START_DATE DATE,
TODO_END_DATE DATE,
TODO_PRIORITY VARCHAR2(15),
TODO_NOTE VARCHAR2(500),
TODO_COMPLETE VARCHAR2(15) DEFAULT 'N'
);

ALTER TABLE TODO_LIST_TABLE
ADD CONSTRAINT PK_TODO_NO PRIMARY KEY(TODO_NO);

ALTER TABLE TODO_LIST_TABLE
ADD CONSTRAINT FK_TODO_CATEGORY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY_TABLE;

CREATE SEQUENCE TODO_SEQ -- 시퀀스 이름
START WITH 1000  --1부터 시작
INCREMENT BY 1 --1씩 증가
NOMAXVALUE  --한계가 없이
NOMINVALUE; --최소값 X

--TODO 추가 쿼리
INSERT INTO TODO_LIST_TABLE
VALUES (TODO_SEQ.NEXTVAL ,2001, 'LIST 01', SYSDATE, SYSDATE, 'M', 'TEST NOTE 1212', 'N');
 
COMMIT; 

SELECT * FROM TODO_LIST_TABLE;

DROP TABLE TODO_LIST_TABLE;



-------------------------------------------------------

CREATE TABLE TODO_MEMBER_TABLE(
TODO_NO NUMBER,
MEMBER_NICKNAME VARCHAR2(50)
);

DROP TABLE TODO_MEMBER_TABLE;

ALTER TABLE TODO_MEMBER_TABLE
ADD CONSTRAINT FK_TODO_MEMBER_NO FOREIGN KEY(TODO_NO) REFERENCES TODO_LIST_TABLE;


SELECT * FROM TODO_MEMBER_TABLE;




