--USER_TABLE 생성
CREATE TABLE USER_TABLE(
USER_ID VARCHAR2(50) NOT NULL,
USER_PW VARCHAR2(20) NOT NULL,
USER_NAME VARCHAR2(20) NOT NULL,
USER_PHONE VARCHAR2(20), 
USER_JOINDATE DATE NOT NULL
);

--PK 설정 USER_TABLE(USER_ID)
ALTER TABLE USER_TABLE
ADD CONSTRAINT PK_USER_ID PRIMARY KEY(USER_ID);

commit;

--유저 회원가입 쿼리
INSERT INTO USER_TABLE(USER_ID, USER_PW, USER_NAME, USER_PHONE, USER_JOINDATE)
VALUES('5', '1', 'stanname닉네임', 'phone012345-67890', sysdate);

--유저 삭제 쿼리
DELETE FROM USER_TABLE
WHERE USER_ID = 'testId';

--유저 로그인 쿼리
SELECT USER_ID, USER_NAME, SYSDATE AS LOGINDATE
FROM USER_TABLE
WHERE USER_ID = 'stan' AND USER_PW = 'stan';

--유저 회원가입 중복체크 쿼리
SELECT USER_ID
FROM USER_TABLE
WHERE USER_ID = 'stan';

--유저 회원정보 수정 쿼리
UPDATE USER_TABLE
SET
USER_PW = 'stan2',
USER_NAME = 'stan2',
USER_PHONE = 'stan3'
WHERE USER_ID = 'stan';



rollback;
commit;

delete user_table;

select *
from USER_TABLE;